---

- name: Stop and Disable Firewalld
  when: ansible_os_family == "RedHat"
  systemd:
     name: firewalld
     daemon_reload: no
     state: stopped
     enabled: no

- name: Install Docker container engine
  include_tasks: pkg.yml
  tags:
    - docker

- name: Enable and restart Docker engine
  systemd:
     name: docker
     daemon_reload: yes
     state: restarted
     enabled: yes
  register: started_docker
  tags:
    - docker
    
- name: Add users to docker group
  user:
    name: '{{ item }}'
    groups: docker
    append: yes
  with_list: '{{ docker_users }}'
  tags:
    - docker

- name: Download docker-compose
  get_url:
    url: https://dl.bintray.com/docker-compose/master/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
  tags:
    - compose