---
- name: apt | Install apt-transport-https
  when: ansible_os_family == "Debian"
  apt:
    name: "apt-transport-https"
    state: present
  tags:
    - docker-engine

- name: apt | Add Docker APT GPG key
  when: ansible_os_family == "Debian"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  tags:
    - docker-engine

- name: apt | Add Docker APT repository
  when: ansible_os_family == "Debian"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    filename: 'docker'
  tags:
    - docker-engine

- name: apt | Install docker engine (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt:
    update_cache: yes
    name: "docker-ce={{ docker_version }}"
    state: present
    force: yes
  tags:
    - docker-engine

# - name: apt | Hold docker version
#   when: ansible_os_family == "Debian"
#   dpkg_selections:
#     name: docker
#     selection: hold
#   tags:
#     - docker-engine

- name: rpm | Create 'dockerurl' vars file
  when: ansible_os_family == "RedHat"
  copy:
    dest: "/etc/yum/vars/dockerurl"
    content: |
        https://storebits.docker.com/ee/linux/{{ license_key }}/centos
  tags:
    - docker-engine

- name: rpm | Install Docker repository
  when: ansible_os_family == "RedHat"
  shell: yum-config-manager \
    --add-repo \
    "https://storebits.docker.com/ee/linux/{{ license_key }}/centos/docker-ee.repo"
  tags:
    - docker-engine

- name: rpm | Install the gpg key
  when: ansible_os_family == "RedHat"
  rpm_key:
    state: present
    key: "https://storebits.docker.com/ee/linux/{{ license_key }}/rhel/gpg"
  tags:
    - docker-engine

- name: rpm | Install Docker EE repository
  when: ansible_os_family == "RedHat"
  shell: yum-config-manager \
    --enable {{ docker_version }}
  tags:
    - docker-engine

- name: rpm | Get the Docker engine
  when: ansible_os_family == "RedHat"
  yum:
    name: docker
    state: present
  tags:
    - docker-engine